server:
  port: ${PORT:9099}
bs23:
  microservices: config-service,edge-gateway,edge-service,edge,guardian,discovery-eureka
spring:
  application:
    name: edge-gateway
  config:
    import: optional:configserver:http://localhost:9091/
logging:
  level:
    org:
      zalando:
        logbook: OFF
eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:9092/eureka/
management:
  endpoints:
    web:
      exposure:
        include: info
